import dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })
import { neon } from '@neondatabase/serverless'
import bcrypt from 'bcryptjs'

const sql = neon(process.env.DATABASE_URL!)

const seedUsers = [
  { email: 'haojun.see@gmail.com', password: 'pcw2hj2026', name: 'HaoJun', role: 'hj' },
  { email: 'clarakhoo@gmail.com', password: 'pcw2ck2026', name: 'Clara', role: 'ck' },
  { email: 'thaodien323@gmail.com', password: 'pcw2family2026', name: 'Grandpa', role: 'family' },
]

const tripDays = [
  { date: "2026-05-17", day_label: "17 May (Sun)", city: "Vienna", accom_name: "WF-Apartment Westbahnhof", accom_checkin: "Check-in: 3pm", accom_checkout: null, accom_address: "5 Dingelstedtgasse, 15. Rudolfsheim-Fünfhaus, 1150 Vienna, Austria", accom_lat: 48.1927, accom_lng: 16.3367, family_activity: "St. Stephen's Cathedral (next to Jewish Museum)", boys_activity: null, ck_site_name: "Jewish Museum of the City of Vienna", ck_site_address: "Dorotheergasse 11, 1010 Vienna, Austria", ck_site_lat: 48.2079, ck_site_lng: 16.3694, hj_networking: "Sunday — ViennaUP WarmUP day. Register at viennaup.com. Many events free. Wristband at first event unlocks free food, wine, coffee at Homebase and Café Spaces. Check WarmUP schedule for Sunday evening events.", remarks: null, transit_note: null },
  { date: "2026-05-18", day_label: "18 May (Mon)", city: "Vienna", accom_name: "WF-Apartment Westbahnhof", accom_checkin: null, accom_checkout: null, accom_address: "5 Dingelstedtgasse, 15. Rudolfsheim-Fünfhaus, 1150 Vienna, Austria", accom_lat: 48.1927, accom_lng: 16.3367, family_activity: "Stadtpark + Natural History Museum", boys_activity: "Same Stadtpark/Burggarten base. Natural History Museum (short walk): giant dinosaur skeletons, virtual conductor game where kids lead the Vienna Philharmonic, staircase that plays piano notes as you walk on it.", ck_site_name: "Jewish Museum of the City of Vienna + Museum of Military History", ck_site_address: "Dorotheergasse 11, 1010 Vienna, Austria", ck_site_lat: 48.2079, ck_site_lng: 16.3694, hj_networking: "ViennaUP main festival starts (18–22 May). Five tracks — one specifically for AI and deeptech. Global Digital Asset Forum 18–22 May. EA Conference (student entrepreneurship) 18 May. Go to viennaup.com, pick events and block calendar for the week.", remarks: "ViennaUP — viennaup.com", transit_note: null },
  { date: "2026-05-19", day_label: "19 May (Tue)", city: "Vienna", accom_name: "WF-Apartment Westbahnhof", accom_checkin: null, accom_checkout: null, accom_address: "5 Dingelstedtgasse, 15. Rudolfsheim-Fünfhaus, 1150 Vienna, Austria", accom_lat: 48.1927, accom_lng: 16.3367, family_activity: "Haus des Meeres — giant aquarium inside a WWII anti-aircraft tower", boys_activity: "Haus des Meeres: multi-level tropical house with free-ranging birds and monkeys, crocodiles, snakes and sharks, 120m² shark aquarium. Rooftop restaurant for 360° views. 6th district — about 15 min from Stadtpark by U-Bahn.", ck_site_name: "Jewish Museum of the City of Vienna", ck_site_address: "Dorotheergasse 11, 1010 Vienna, Austria", ck_site_lat: 48.2079, ck_site_lng: 16.3694, hj_networking: "ViennaUP Day 2. 'From Pitch to Patient' event — startups, healthcare professionals and experts exploring how digital health and AI solutions move from concept to clinical implementation.", remarks: null, transit_note: null },
  { date: "2026-05-20", day_label: "20 May (Wed)", city: "Vienna", accom_name: "WF-Apartment Westbahnhof", accom_checkin: null, accom_checkout: null, accom_address: "5 Dingelstedtgasse, 15. Rudolfsheim-Fünfhaus, 1150 Vienna, Austria", accom_lat: 48.1927, accom_lng: 16.3367, family_activity: "St. Charles's Church (Karlskirche), Kinderspielplatz playground", boys_activity: "Karlskirche area — Kinderspielplatz behind the church, steps from Karlsplatz metro: wooden climbing structures, slides, ladders, wooden bridge, plenty of shade and benches. Then coffee at cafes around Karlsplatz.", ck_site_name: "Historical Hitler Walking Tour 2:30–5pm (TBC)", ck_site_address: "Vienna 1st district, Ringstrasse area", ck_site_lat: 48.2040, ck_site_lng: 16.3640, hj_networking: "PeaceTech Conference 2026 — 20 May at Impact Hub Vienna as part of ViennaUP. Explores ethical AI, sustainability, digital governance. 'Pitch & Chill' session where AI startups pitch to investors. Direct AI networking opportunity.", remarks: "PeaceTech Conference", transit_note: null },
  { date: "2026-05-21", day_label: "21 May (Thu)", city: "Vienna", accom_name: "WF-Apartment Westbahnhof", accom_checkin: null, accom_checkout: null, accom_address: "5 Dingelstedtgasse, 15. Rudolfsheim-Fünfhaus, 1150 Vienna, Austria", accom_lat: 48.1927, accom_lng: 16.3367, family_activity: "Stay in / Chill nearby", boys_activity: "Full day without CK. Schönbrunn Palace + Zoo — world's oldest zoo, Schönbrunn Labyrinthikon playground has 14 separate play areas. Easy by U4 from 10th district. Full day.", ck_site_name: "Mauthausen Concentration Camp Memorial — 8hrs full day (booked)", ck_site_address: "Erinnerungsstrasse 1, 4310 Mauthausen, Austria", ck_site_lat: 48.2556, ck_site_lng: 14.5057, hj_networking: "ViennaUP Day 4 — full day, best window to attend events independently. Also: AI Factory Austria (AI:AT) Coworking Hub at SOLARIS, Karl-Farkas-Gasse, Landstraße — drop in and introduce yourself.", remarks: "Mauthausen Tour *booked", transit_note: null },
  { date: "2026-05-22", day_label: "22 May (Fri)", city: "Vienna", accom_name: "WF-Apartment Westbahnhof", accom_checkin: null, accom_checkout: null, accom_address: "5 Dingelstedtgasse, 15. Rudolfsheim-Fünfhaus, 1150 Vienna, Austria", accom_lat: 48.1927, accom_lng: 16.3367, family_activity: "Schönbrunn Palace & Zoo", boys_activity: "If Schönbrunn was done on 21 May, do Wachau — scenic Danube valley 90 min by train from Vienna. Beautiful and manageable with kids. Or use as a rest day.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "ViennaUP last day (Day 5). Close out Vienna networking. Exchange contacts and arrange follow-ups before leaving Vienna on Saturday.", remarks: null, transit_note: null },
  { date: "2026-05-23", day_label: "23 May (Sat)", city: "Vienna", accom_name: "WF-Apartment Westbahnhof", accom_checkin: null, accom_checkout: "Check-out: 11am", accom_address: "5 Dingelstedtgasse, 15. Rudolfsheim-Fünfhaus, 1150 Vienna, Austria", accom_lat: 48.1927, accom_lng: 16.3367, family_activity: "Rest day to pack", boys_activity: "Pack and check out. Vienna → Bratislava is about 1 hour by car. Transit day.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: null, remarks: null, transit_note: "Drive Vienna → Bratislava ~1 hour" },
  { date: "2026-05-24", day_label: "24 May (Sun)", city: "Bratislava", accom_name: "Old Town Apartment", accom_checkin: "Check-in: 3pm", accom_checkout: null, accom_address: "Dunajská 3B floor 3, 811 08 Bratislava, Slovakia", accom_lat: 48.1434, accom_lng: 17.1077, family_activity: "The Blue Church (10 min walk), Danube Riverfront", boys_activity: "The Blue Church — beautiful fairytale-blue church, boys will be fascinated. Walk Old Town — hunt for quirky statues (Čumil the Sewer Worker). Danube riverfront: Magio Beach or Pláž Staré Mesto have artificial beaches great for kids.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "Sunday arrival. Rest and observe. Bratislava's tech scene is small — mostly multinational offices (IBM, Accenture, Dell). No major AI events. Use evening for LinkedIn outreach to Slovak founders, set up coffee meetings for Mon–Tue.", remarks: null, transit_note: null },
  { date: "2026-05-25", day_label: "25 May (Mon)", city: "Bratislava", accom_name: "Old Town Apartment", accom_checkin: null, accom_checkout: null, accom_address: "Dunajská 3B floor 3, 811 08 Bratislava, Slovakia", accom_lat: 48.1434, accom_lng: 17.1077, family_activity: "Aurelium Science Centre or SNM Natural History Museum", boys_activity: "Bratislava Castle — short uphill walk from Old Town, close to CK's museum. Castle grounds free, well-equipped playground, gardens with city views, restaurant/café on site. Walk back through Old Town for lunch at riverfront café. Eurovea shopping centre nearby — waterfront promenade, playground, cafes.", ck_site_name: "Museum of Jewish Culture", ck_site_address: "Heydukova 11-13, 811 08 Bratislava, Slovakia", ck_site_lat: 48.1468, ck_site_lng: 17.1080, hj_networking: "Monday — best day for meetings. Bratislava coworking at Coworking Club and HubHub. Walk in, buy day pass, see who's around. Post on LinkedIn that you're in Bratislava interested in connecting with AI founders.", remarks: null, transit_note: null },
  { date: "2026-05-26", day_label: "26 May (Tue)", city: "Bratislava", accom_name: "Old Town Apartment", accom_checkin: null, accom_checkout: null, accom_address: "Dunajská 3B floor 3, 811 08 Bratislava, Slovakia", accom_lat: 48.1434, accom_lng: 17.1077, family_activity: "Bratislava Castle or DinoPark @ zoo", boys_activity: "Bratislava Zoo + DinoPark — €27 family ticket. DinoPark has life-sized moving dinosaur models. Lots of picnic areas and playground. Alternative: Horáreň Horský Park — animals (geese, pig, bunnies), playground, small bikes and motorcycles to borrow free, coffee shop with lemonades and vegan popsicles.", ck_site_name: "Museum of Jewish Culture", ck_site_address: "Heydukova 11-13, 811 08 Bratislava, Slovakia", ck_site_lat: 48.1468, ck_site_lng: 17.1080, hj_networking: "Follow up on Monday's contacts.", remarks: null, transit_note: null },
  { date: "2026-05-27", day_label: "27 May (Wed)", city: "Bratislava", accom_name: "Old Town Apartment", accom_checkin: null, accom_checkout: "Check-out: 10am", accom_address: "Dunajská 3B floor 3, 811 08 Bratislava, Slovakia", accom_lat: 48.1434, accom_lng: 17.1077, family_activity: "BIBIANA international house of art for children (11 min tram ride)", boys_activity: "Morning only before departure. BIBIANA or final riverside walk + crepes at Danube café. Keep simple — packing and leaving.", ck_site_name: "Sered Concentration Camp Tour (TBC)", ck_site_address: "Múzeum holokaustu, 925 71 Šereď, Slovakia", ck_site_lat: 48.2887, ck_site_lng: 17.7320, hj_networking: null, remarks: null, transit_note: "Drive Bratislava → Győr (afternoon departure)" },
  { date: "2026-05-28", day_label: "28 May (Thu)", city: "Győr", accom_name: "Eden Center Home", accom_checkin: "Check-in: 2pm", accom_checkout: "Check-out: 10am", accom_address: "9021 Győr, Czuczor Gergely u. 15., Hungary", accom_lat: 47.6850, accom_lng: 17.6358, family_activity: "Győr War Memorial Fountain along the Rába River", boys_activity: "Rába riverside walk — kids can run freely. Old Town compact and walkable. Grab pastries from a local bakery and sit by the river.", ck_site_name: "Mid-point consolidation (working from base)", ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "Győr is home to the huge Audi manufacturing plant. Not a startup hub. Good for writing LinkedIn connection messages, researching Budapest contacts, preparing for next city.", remarks: "Look up Impact Hub Budapest, Kaptár coworking, and Design Terminal. Find Budapest AI meetup groups on Meetup.com and Eventbrite and RSVP to anything happening during 30 May–4 Jun window.", transit_note: null },
  { date: "2026-05-29", day_label: "29 May (Fri)", city: "Győr", accom_name: "Eden Center Home", accom_checkin: null, accom_checkout: "Check-out: 10am", accom_address: "9021 Győr, Czuczor Gergely u. 15., Hungary", accom_lat: 47.6850, accom_lng: 17.6358, family_activity: "Győr Cathedral & Old Town Area", boys_activity: "Full Old Town together as family — small, beautiful and easy with kids. Rába riverside again good for running around. Very relaxed day.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "Pre-arrival research for Budapest. Look up Impact Hub Budapest, Kaptár coworking, and Design Terminal. Find Budapest AI meetup groups on Meetup.com and Eventbrite and RSVP to anything happening during 30 May–4 Jun window.", remarks: null, transit_note: null },
  { date: "2026-05-30", day_label: "30 May (Sat)", city: "Budapest", accom_name: "Gentleman Apartment", accom_checkin: "Check-in: 4pm", accom_checkout: null, accom_address: "1073 Budapest, 4 Kertész utca, Hungary", accom_lat: 47.5020, accom_lng: 19.0650, family_activity: "Shoes on the Danube Bank, Erzsébet Square", boys_activity: "Erzsébet Square — skate park, water fountains, playground, Budapest Eye Ferris wheel (2,400 HUF adults, 1,500 HUF children 2–14). Great soft landing for the boys after a travel day.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "Weekend, settle in. Budapest AI startups raised €300 million in 2024. Key hubs: Impact Hub Budapest and Kaptár. Plan visits for weekdays ahead.", remarks: null, transit_note: "Drive/travel Győr → Budapest" },
  { date: "2026-05-31", day_label: "31 May (Sun)", city: "Budapest", accom_name: "Gentleman Apartment", accom_checkin: null, accom_checkout: null, accom_address: "1073 Budapest, 4 Kertész utca, Hungary", accom_lat: 47.5020, accom_lng: 19.0650, family_activity: "Margaret Island", boys_activity: "Margaret Island — playgrounds, musical fountain, small zoo, Japanese garden. Rent bikes or pedal cart. Palatinus Baths for a full day in the water. Free to enter, just pay for activities. Full day here.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "St. Stephen's Basilica + Soviet War Memorial nearby.", remarks: null, transit_note: null },
  { date: "2026-06-01", day_label: "1 Jun (Mon)", city: "Budapest", accom_name: "Gentleman Apartment", accom_checkin: null, accom_checkout: null, accom_address: "1073 Budapest, 4 Kertész utca, Hungary", accom_lat: 47.5020, accom_lng: 19.0650, family_activity: "St. Stephen's Basilica + Soviet War Memorial", boys_activity: "Holocaust Memorial Center in Ferencváros (9th district). About 1km away: National Museum gardens — café and playground (Múzeum kert). Pastry shop from Auguszt confectionary family in renovated guard house. Play corner inside, playground outside.", ck_site_name: "Holocaust Memorial Center", ck_site_address: "Páva u. 39, 1094 Budapest, Hungary", ck_site_lat: 47.4878, ck_site_lng: 19.0620, hj_networking: "Monday — Design Terminal (Müpa Budapest area, 9th district). Hungary's key startup support organisation. Walk in, ask about open events. Also try Kaptár coworking (1053 Budapest, Semmelweis u. 19).", remarks: null, transit_note: null },
  { date: "2026-06-02", day_label: "2 Jun (Tue)", city: "Budapest", accom_name: "Gentleman Apartment", accom_checkin: null, accom_checkout: null, accom_address: "1073 Budapest, 4 Kertész utca, Hungary", accom_lat: 47.5020, accom_lng: 19.0650, family_activity: "City Park + Városliget playground + Zoo or Balloon Ride", boys_activity: "Városliget playground — Budapest's biggest, 13,000m². Multi-level climbing towers, giant slides, rope bridges, water lock stream, zip line. Budapest Zoo (oldest in world, petting zoo, Holnemvolt Castle for small children). Városliget Café has dedicated kids' menu.", ck_site_name: "Holocaust Memorial Center", ck_site_address: "Páva u. 39, 1094 Budapest, Hungary", ck_site_lat: 47.4878, ck_site_lng: 19.0620, hj_networking: "Continue Budapest networking. Budapest Startup Safari events if any on. Cold-reach AI founders via LinkedIn with 'I'm in Budapest this week' message.", remarks: null, transit_note: null },
  { date: "2026-06-03", day_label: "3 Jun (Wed)", city: "Budapest", accom_name: "Gentleman Apartment", accom_checkin: null, accom_checkout: null, accom_address: "1073 Budapest, 4 Kertész utca, Hungary", accom_lat: 47.5020, accom_lng: 19.0650, family_activity: "Buda Castle or Riso Ristorante near the Vienna Gate", boys_activity: "Buda Castle District — Budavári Mátyás Király playground with medieval theme. Or Riso Ristorante near Vienna Gate — children's playground in garden terrace, can admire Buda Castle views, sip coffee while kids are entertained.", ck_site_name: "Holocaust Memorial Center", ck_site_address: "Páva u. 39, 1094 Budapest, Hungary", ck_site_lat: 47.4878, ck_site_lng: 19.0620, hj_networking: "Final Budapest networking push. Arrange any evening drinks with founders or investors connected with this week.", remarks: null, transit_note: null },
  { date: "2026-06-04", day_label: "4 Jun (Thu)", city: "Budapest", accom_name: "Gentleman Apartment", accom_checkin: null, accom_checkout: "Check-out: 10am", accom_address: "1073 Budapest, 4 Kertész utca, Hungary", accom_lat: 47.5020, accom_lng: 19.0650, family_activity: "Rest day to pack", boys_activity: "Check-out 10am. Travel day. Walk Andrássy Boulevard. Boys can see House of Terror from outside. Then depart.", ck_site_name: "House of Terror Museum", ck_site_address: "Andrássy út 60, 1062 Budapest, Hungary", ck_site_lat: 47.5115, ck_site_lng: 19.0662, hj_networking: null, remarks: "Pack @ night", transit_note: "Travel Budapest → Warsaw" },
  { date: "2026-06-05", day_label: "5 Jun (Fri)", city: "Warsaw", accom_name: "Hostel Coco", accom_checkin: "Check-in: 2pm", accom_checkout: "Check-out: 11am", accom_address: "Al. Jerozolimskie 107, Ochota, 02-011 Warsaw, Poland", accom_lat: 52.2210, accom_lng: 20.9986, family_activity: "Museum of Evolution / Palace of Culture & Science", boys_activity: "Saxon Garden (Ogród Saski) — few minutes from Centrum station. Popular park with excellent playgrounds. Café nearby.", ck_site_name: "Warsaw Uprising Museum", ck_site_address: "Grzybowska 79, 00-844 Warsaw, Poland", ck_site_lat: 52.2317, ck_site_lng: 20.9806, hj_networking: "Friday arrival. Warsaw has Google for Startups Campus, The Heart (38th floor Warsaw Spire), IBM AI research hub. Look up Friday evening events on Meetup.com Warsaw.", remarks: null, transit_note: null },
  { date: "2026-06-06", day_label: "6 Jun (Sat)", city: "Warsaw", accom_name: "Hostel Coco", accom_checkin: null, accom_checkout: "Check-out: 11am", accom_address: "Al. Jerozolimskie 107, Ochota, 02-011 Warsaw, Poland", accom_lat: 52.2210, accom_lng: 20.9986, family_activity: "Łazienki Park", boys_activity: "Łazienki Park — new playground with sections for specific age ranges including water area. Free Chopin piano recitals in summer (picnic on grass). Animals (peacocks, ducks, squirrels) roam freely.", ck_site_name: "POLIN Museum of the History of Polish Jews", ck_site_address: "Anielewicza 6, 00-157 Warsaw, Poland", ck_site_lat: 52.2498, ck_site_lng: 20.9938, hj_networking: "Warsaw.AI community — regular meetups for AI practitioners in collaboration with Google. Deep dive tech talks on AI, GenAI, LLMs and Agents, plus networking. Check warsaw.ai for next event.", remarks: "Pack @ night", transit_note: "Travel Warsaw → Kraków (Sunday morning)" },
  { date: "2026-06-07", day_label: "7 Jun (Sun)", city: "Kraków", accom_name: "Apartmenty Delecta", accom_checkin: "Check-in: 3pm", accom_checkout: null, accom_address: "ul. Limanowskiego 11A, Podgórze, 30-551 Kraków, Poland", accom_lat: 50.0440, accom_lng: 19.9477, family_activity: "Vistula River / Bridge", boys_activity: "Vistula riverfront near accommodation — walk the bridges, grab ice cream. Planty Park (15 min walk) great for kids to run. Settle in for the evening.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "Sunday arrival. London Tech Week runs 8–12 June — register for hybrid/online sessions. Note: Kraków Technology Park and Hub:raum are notable incubators.", remarks: null, transit_note: null },
  { date: "2026-06-08", day_label: "8 Jun (Mon)", city: "Kraków", accom_name: "Apartmenty Delecta", accom_checkin: null, accom_checkout: null, accom_address: "ul. Limanowskiego 11A, Podgórze, 30-551 Kraków, Poland", accom_lat: 50.0440, accom_lng: 19.9477, family_activity: "Old Town / Museum Banksy", boys_activity: "Jordan Park (Park Jordana) — large public park along Vistula with big playground, football pitches, cycling paths. Or walk Kazimierz neighbourhood — colourful, interesting, plenty of cafes with outdoor seating.", ck_site_name: "Galicia Jewish Museum + Oskar Schindler's Enamel Factory & Eagle Pharmacy", ck_site_address: "Dajwór 18, 31-052 Kraków, Poland", ck_site_lat: 50.0522, ck_site_lng: 19.9480, hj_networking: "Monday. Key players: Innovation Nest (SaaS/B2B focus), MassChallenge Kraków, Hub:raum Kraków (Deutsche Telekom-backed). Try to drop into one — Innovation Nest is particularly welcoming to visiting founders.", remarks: "Krakow Technology Park + Innovation Nest", transit_note: null },
  { date: "2026-06-09", day_label: "9 Jun (Tue)", city: "Kraków", accom_name: "Apartmenty Delecta", accom_checkin: null, accom_checkout: null, accom_address: "ul. Limanowskiego 11A, Podgórze, 30-551 Kraków, Poland", accom_lat: 50.0440, accom_lng: 19.9477, family_activity: "Bricks & Figs — LEGO Museum", boys_activity: "Bricks & Figs LEGO Museum — highlight for both 6 and 10 year old. Kraków Old Town area. Do in morning, then lunch in Old Town. Rynek Główny (Main Market Square) has outdoor cafe seating and buskers.", ck_site_name: "Galicia Jewish Museum + Oskar Schindler's Enamel Factory & Eagle Pharmacy", ck_site_address: "Dajwór 18, 31-052 Kraków, Poland", ck_site_lat: 50.0522, ck_site_lng: 19.9480, hj_networking: "Kraków has highest concentration of ICT specialists in Poland — over 100,000 specialists. Walk into Kraków Technology Park (ul. Podole 60) — open campus with dozens of tech companies.", remarks: null, transit_note: null },
  { date: "2026-06-10", day_label: "10 Jun (Wed)", city: "Kraków", accom_name: "Apartmenty Delecta", accom_checkin: null, accom_checkout: null, accom_address: "ul. Limanowskiego 11A, Podgórze, 30-551 Kraków, Poland", accom_lat: 50.0440, accom_lng: 19.9477, family_activity: "Stay in / Chill nearby. Zabawa i Wiedza hands-on science museum.", boys_activity: "CK gone all day. Best option: Kraków Zoo in Wolski Forest (30 min by bus). Large zoo in natural wooded surroundings — pack a picnic. Or closer: Zabawa i Wiedza (Play and Knowledge Interactive Museum).", ck_site_name: "Kraków Auschwitz Tour — CK gone all day", ck_site_address: "Więźniów Oświęcimia 20, 32-603 Oświęcim, Poland", ck_site_lat: 50.0274, ck_site_lng: 19.2038, hj_networking: "Full day for yourself. Set up two coffee meetings in morning, explore Hub:raum or Innovation Nest in afternoon.", remarks: null, transit_note: null },
  { date: "2026-06-11", day_label: "11 Jun (Thu)", city: "Kraków", accom_name: "Apartmenty Delecta", accom_checkin: null, accom_checkout: null, accom_address: "ul. Limanowskiego 11A, Podgórze, 30-551 Kraków, Poland", accom_lat: 50.0440, accom_lng: 19.9477, family_activity: "St. Joseph's Church / Park", boys_activity: "Botanical Garden of Jagiellonian University (ul. Kopernika 27) — one of the oldest botanical gardens in Poland. Kids love exotic plants, carnivorous plants, giant cacti and banana trees. Walkable from Podgórze via the bridge. Small café on site.", ck_site_name: "Galicia Jewish Museum + Oskar Schindler's Enamel Factory & Eagle Pharmacy", ck_site_address: "Dajwór 18, 31-052 Kraków, Poland", ck_site_lat: 50.0522, ck_site_lng: 19.9480, hj_networking: "Final Kraków networking day. Any follow-up coffees with people met earlier in the week.", remarks: null, transit_note: null },
  { date: "2026-06-12", day_label: "12 Jun (Fri)", city: "Kraków", accom_name: "Apartmenty Delecta", accom_checkin: null, accom_checkout: "Check-out: 10am", accom_address: "ul. Limanowskiego 11A, Podgórze, 30-551 Kraków, Poland", accom_lat: 50.0440, accom_lng: 19.9477, family_activity: "Rest day to pack", boys_activity: "Morning packing. Check-out 10am → airport → Kraków to Paris 10am flight, arrive 12:30pm.", ck_site_name: "Galicia Jewish Museum + Oskar Schindler's Enamel Factory & Eagle Pharmacy", ck_site_address: "Dajwór 18, 31-052 Kraków, Poland", ck_site_lat: 50.0522, ck_site_lng: 19.9480, hj_networking: null, remarks: null, transit_note: "Flight Kraków → Paris 10am (arrive 12:30pm)" },
  { date: "2026-06-13", day_label: "13 Jun (Sat)", city: "Paris", accom_name: "Les Lilas Service Apartments", accom_checkin: "Check-in: 3pm", accom_checkout: null, accom_address: "6 Rue Lucien Noël, Les Lilas, 93260", accom_lat: 48.8780, accom_lng: 2.4180, family_activity: "Basilique du Sacré-Cœur de Montmartre, Square Louise Michel", boys_activity: "Sacré-Cœur — the steps, buskers, views. Below the basilica, Square Louise Michel has park with small carousel and green lawn. Wander Montmartre's streets. Very alive on Saturday afternoon.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "Weekend arrival. Station F just launched F/ai — world's biggest startup campus, home to over 1,000 startups. Plan visit for Monday.", remarks: "Look for any La French Tech networking events this week.", transit_note: null },
  { date: "2026-06-14", day_label: "14 Jun (Sun)", city: "Paris", accom_name: "Les Lilas Service Apartments", accom_checkin: null, accom_checkout: null, accom_address: "6 Rue Lucien Noël, Les Lilas, 93260", accom_lat: 48.8780, accom_lng: 2.4180, family_activity: "Notre-Dame Cathedral / Sainte-Chapelle", boys_activity: "Le Marais — Square du Temple–Élie Wiesel (64 Rue de Bretagne): large playground with slides, climbing structures, grass and benches. Place des Vosges — oldest square in Paris, fountain in centre, families picnic. Breizh Café in Le Marais for outstanding Brittany crepes.", ck_site_name: "Mémorial de la Shoah", ck_site_address: "17 Rue Geoffroy l'Asnier, 75004 Paris, France", ck_site_lat: 48.8549, ck_site_lng: 2.3526, hj_networking: "Sunday. Plan Station F strategy for Monday.", remarks: null, transit_note: null },
  { date: "2026-06-15", day_label: "15 Jun (Mon)", city: "Paris", accom_name: "Les Lilas Service Apartments", accom_checkin: null, accom_checkout: null, accom_address: "6 Rue Lucien Noël, Les Lilas, 93260", accom_lat: 48.8780, accom_lng: 2.4180, family_activity: "Aquarium de Paris opposite Eiffel Tower", boys_activity: "Aquarium de Paris (Trocadéro) — sharks, tropical fish, touch pools. Then Champ de Mars — huge park below Eiffel Tower with playground (swings, slides, climbing frames, sandpit). Snack at stand next to carousel.", ck_site_name: "Mémorial de la Shoah", ck_site_address: "17 Rue Geoffroy l'Asnier, 75004 Paris, France", ck_site_lat: 48.8549, ck_site_lng: 2.3526, hj_networking: "Go to Station F today. 5 Parvis Alan Turing, 75013 — open to visitors. Home to 1,000+ startups, programs from Google, Meta, LVMH, HEC Paris. F/ai program for early-stage AI startups. Walk in, visit café, attend open events, talk to founders.", remarks: null, transit_note: null },
  { date: "2026-06-16", day_label: "16 Jun (Tue)", city: "Paris", accom_name: "Les Lilas Service Apartments", accom_checkin: null, accom_checkout: null, accom_address: "6 Rue Lucien Noël, Les Lilas, 93260", accom_lat: 48.8780, accom_lng: 2.4180, family_activity: "Arc de Triomphe, Jardin du Luxembourg playground", boys_activity: "GP departs 11:25am. Arc de Triomphe — kids enjoy climbing to top for views. Or Jardin du Luxembourg — playground has zipline, climbing ropes and slides. Stroll through gardens, watch kids float toy boats in pond.", ck_site_name: "Mémorial de la Shoah", ck_site_address: "17 Rue Geoffroy l'Asnier, 75004 Paris, France", ck_site_lat: 48.8549, ck_site_lng: 2.3526, hj_networking: "Follow up on Station F contacts. La French Tech government program. Paris ranks 4th globally as startup hub. Look for La French Tech networking events.", remarks: "GP flight out 11:25am", transit_note: null },
  { date: "2026-06-17", day_label: "17 Jun (Wed)", city: "Paris", accom_name: "Les Lilas Service Apartments", accom_checkin: null, accom_checkout: "Check-out: 11am", accom_address: "6 Rue Lucien Noël, Les Lilas, 93260", accom_lat: 48.8780, accom_lng: 2.4180, family_activity: "La Villette — Urban Cultural Park, Dragon Playground", boys_activity: "La Villette — Cité des Sciences et de l'Industrie (interactive science museum for kids), huge park, Dragon Playground (giant dragon you can walk through and slide out of). Allow whole morning. Check-out 11am, afternoon is Eurostar prep.", ck_site_name: "Mémorial de la Shoah", ck_site_address: "17 Rue Geoffroy l'Asnier, 75004 Paris, France", ck_site_lat: 48.8549, ck_site_lng: 2.3526, hj_networking: null, remarks: null, transit_note: "Eurostar 12:02pm Paris → London (gate closes 11:02am)" },
  { date: "2026-06-18", day_label: "18 Jun (Thu)", city: "London", accom_name: "The Headlam Apartment", accom_checkin: "Check-in: 3pm", accom_checkout: "Check-out: 10am", accom_address: "Headlam Street, Whitechapel E1, London, E1 5PU", accom_lat: 51.5165, accom_lng: -0.0611, family_activity: "Eurostar 12:02pm (gate closes 11:02am). Southbank walk, Tower Bridge.", boys_activity: "Arrival afternoon. Southbank — outdoor skate park, buskers, river views, Tate Modern turbine hall (free). Or walk over Tower Bridge — glass floor walkway at the top.", ck_site_name: "The Imperial War Museum Holocaust Galleries", ck_site_address: "Lambeth Road, London SE1 6HZ", ck_site_lat: 51.4963, ck_site_lng: -0.1090, hj_networking: "Just arrived into one of the world's biggest AI ecosystems. Shoreditch is 5 minutes from Whitechapel. Evening: find a tech bar or coworking café in Shoreditch (Boxpark nearby). Look up AI Tinkerers London and Mindstone London AI meetup.", remarks: "Start looking up AI Tinkerers London and Mindstone London AI meetup for any events this week.", transit_note: "Eurostar 12:02pm Paris → London (gate closes 11:02am)" },
  { date: "2026-06-19", day_label: "19 Jun (Fri)", city: "London", accom_name: "The Headlam Apartment", accom_checkin: null, accom_checkout: "Check-out: 10am", accom_address: "Headlam Street, Whitechapel E1, London, E1 5PU", accom_lat: 51.5165, accom_lng: -0.0611, family_activity: "GK arrives at Heathrow 6am+", boys_activity: "IWM Park playground (Geraldine Mary Harmsworth Park). Or Queen Elizabeth Olympic Park (Stratford) — Tumbling Bay Playground (natural landscape with sandpits, rock pools, treehouses, wobbly bridges). Timber Lodge café right next to it.", ck_site_name: "The Imperial War Museum Holocaust Galleries", ck_site_address: "Lambeth Road, London SE1 6HZ", ck_site_lat: 51.4963, ck_site_lng: -0.1090, hj_networking: "Shoreditch/Old Street. Walk Silicon Roundabout area. Drop into WeWork or Second Home (Shoreditch) for a day pass. Look up Friday evening networking drinks.", remarks: null, transit_note: null },
  { date: "2026-06-20", day_label: "20 Jun (Sat)", city: "London", accom_name: "2-Bedrm Flat (Bedford)", accom_checkin: "Check-in: 3pm", accom_checkout: "Check-out: 10am", accom_address: "Castle Quay, Castle Lane, Bedford, Bedford, MK40 3FE", accom_lat: 52.1355, accom_lng: -0.4675, family_activity: "Store luggage at St Pancras, day in Bedford", boys_activity: "Bedford is quiet market town on River Great Ouse. Riverside walk with park and playground. Very low-key rest day. Bedford Park has good playground and café.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "Rest day / admin. Prepare London networking plan for the week ahead.", remarks: "Store luggage @ St Pancras", transit_note: null },
  { date: "2026-06-21", day_label: "21 Jun (Sun)", city: "London", accom_name: "Camden Flat", accom_checkin: "Check-in: 3pm", accom_checkout: null, accom_address: "100 Camden Road, London, NW1 9EA", accom_lat: 51.5390, accom_lng: -0.1426, family_activity: null, boys_activity: "Now in Camden. Regent's Park — 10 min walk, playground, boating lake, rose garden. Primrose Hill — panoramic London views. Camden Market — street food, buskers, quirky shops. Sunday is when it's buzzing.", ck_site_name: "The Wiener Holocaust Library", ck_site_address: "4 Devonshire Street, Marylebone, London W1G 7BH", ck_site_lat: 51.5210, ck_site_lng: -0.1444, hj_networking: "Sunday. Walk the area. Wiener Holocaust Library is in Marylebone — about 20 min by tube. Look up any Sunday evening tech meetups.", remarks: null, transit_note: null },
  { date: "2026-06-22", day_label: "22 Jun (Mon)", city: "London", accom_name: "Camden Flat", accom_checkin: null, accom_checkout: null, accom_address: "100 Camden Road, London, NW1 9EA", accom_lat: 51.5390, accom_lng: -0.1426, family_activity: null, boys_activity: "Regent's Park for morning play while you go to meetings. Afternoon: London Zoo (walkable from Camden Road). Boys are at the right age for it.", ck_site_name: "The Wiener Holocaust Library", ck_site_address: "4 Devonshire Street, Marylebone, London W1G 7BH", ck_site_lat: 51.5210, ck_site_lng: -0.1444, hj_networking: "London AI Developers Group — monthly meetup in collaboration with Google, 20,000+ AI developers in London. Check Meetup.com for June dates. AI Tinkerers London — monthly meetup, every demo runs live code. Part of 220-city global network with 101,000+ members.", remarks: null, transit_note: null },
  { date: "2026-06-23", day_label: "23 Jun (Tue)", city: "London", accom_name: "Camden Flat", accom_checkin: null, accom_checkout: null, accom_address: "100 Camden Road, London, NW1 9EA", accom_lat: 51.5390, accom_lng: -0.1426, family_activity: null, boys_activity: "Science Museum (South Kensington — free). Best free museum for kids in the world. Entire floors dedicated to hands-on experiments, space, engineering. Follow with Hyde Park — Diana Memorial Playground: pirate ship, wooden fort, sandy beach. One of the best playgrounds in London.", ck_site_name: "The Wiener Holocaust Library", ck_site_address: "4 Devonshire Street, Marylebone, London W1G 7BH", ck_site_lat: 51.5210, ck_site_lng: -0.1444, hj_networking: "Mindstone London AI Meetup — monthly event, talks, pizza, drinks and networking. RSVP via Meetup.com. Check if June edition falls this week.", remarks: null, transit_note: null },
  { date: "2026-06-24", day_label: "24 Jun (Wed)", city: "London", accom_name: "Camden Flat", accom_checkin: null, accom_checkout: null, accom_address: "100 Camden Road, London, NW1 9EA", accom_lat: 51.5390, accom_lng: -0.1426, family_activity: null, boys_activity: "British Museum (Bloomsbury — 20 min walk from Camden). Egyptian mummies will keep the 6-year-old occupied for hours. Or Tower of London — Crown Jewels and Beefeater guards genuinely exciting for both ages.", ck_site_name: "The Wiener Holocaust Library", ck_site_address: "4 Devonshire Street, Marylebone, London W1G 7BH", ck_site_lat: 51.5210, ck_site_lng: -0.1444, hj_networking: "Final full networking day. Wrap up conversations, share contacts, plant seeds for future collaboration. Evening: farewell drink with anyone connected this week.", remarks: null, transit_note: null },
  { date: "2026-06-25", day_label: "25 Jun (Thu)", city: "London", accom_name: "Camden Flat", accom_checkin: null, accom_checkout: null, accom_address: "100 Camden Road, London, NW1 9EA", accom_lat: 51.5390, accom_lng: -0.1426, family_activity: "Consolidation", boys_activity: "Last full day. Diana Memorial Playground if not done already (free entry, pirate ship in the sand). Then Hyde Park — feed ducks at the Serpentine, rent a pedalo. Ice cream from lakeside vendors.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: "Rest and pack. Final follow-up emails to everyone met across the 40 days.", remarks: null, transit_note: null },
  { date: "2026-06-26", day_label: "26 Jun (Fri)", city: "London", accom_name: "Camden Flat", accom_checkin: null, accom_checkout: "Check-out: 11am", accom_address: "100 Camden Road, London, NW1 9EA", accom_lat: 51.5390, accom_lng: -0.1426, family_activity: "Flight home 11:20am — reach airport by 8:30am", boys_activity: "Topy + GK 11:20am flight home to Singapore.", ck_site_name: null, ck_site_address: null, ck_site_lat: null, ck_site_lng: null, hj_networking: null, remarks: null, transit_note: "Flight to Singapore 11:20am — airport by 8:30am" },
]

const ckResearchEntries = [
  { date: "2026-05-17", site_name: "Jewish Museum of the City of Vienna", site_city: "Vienna", site_country: "Austria", lat: 48.2079, lng: 16.3694, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "May 2026" },
  { date: "2026-05-18", site_name: "Jewish Museum of the City of Vienna", site_city: "Vienna", site_country: "Austria", lat: 48.2079, lng: 16.3694, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "May 2026" },
  { date: "2026-05-19", site_name: "Jewish Museum of the City of Vienna", site_city: "Vienna", site_country: "Austria", lat: 48.2079, lng: 16.3694, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "May 2026" },
  { date: "2026-05-20", site_name: "Historical Hitler Walking Tour Vienna", site_city: "Vienna", site_country: "Austria", lat: 48.2040, lng: 16.3640, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "May 2026" },
  { date: "2026-05-21", site_name: "Mauthausen Concentration Camp Memorial", site_city: "Mauthausen", site_country: "Austria", lat: 48.2556, lng: 14.5057, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "May 2026" },
  { date: "2026-05-25", site_name: "Museum of Jewish Culture Bratislava", site_city: "Bratislava", site_country: "Slovakia", lat: 48.1468, lng: 17.1080, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "May 2026" },
  { date: "2026-05-26", site_name: "Museum of Jewish Culture Bratislava", site_city: "Bratislava", site_country: "Slovakia", lat: 48.1468, lng: 17.1080, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "May 2026" },
  { date: "2026-05-27", site_name: "Sered Concentration Camp Memorial", site_city: "Sered", site_country: "Slovakia", lat: 48.2887, lng: 17.7320, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "May 2026" },
  { date: "2026-06-01", site_name: "Holocaust Memorial Center Budapest", site_city: "Budapest", site_country: "Hungary", lat: 47.4878, lng: 19.0620, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-02", site_name: "Holocaust Memorial Center Budapest", site_city: "Budapest", site_country: "Hungary", lat: 47.4878, lng: 19.0620, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-03", site_name: "Holocaust Memorial Center Budapest", site_city: "Budapest", site_country: "Hungary", lat: 47.4878, lng: 19.0620, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-04", site_name: "House of Terror Museum Budapest", site_city: "Budapest", site_country: "Hungary", lat: 47.5115, lng: 19.0662, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-05", site_name: "Warsaw Uprising Museum", site_city: "Warsaw", site_country: "Poland", lat: 52.2317, lng: 20.9806, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-06", site_name: "POLIN Museum of the History of Polish Jews", site_city: "Warsaw", site_country: "Poland", lat: 52.2498, lng: 20.9938, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-08", site_name: "Galicia Jewish Museum", site_city: "Krakow", site_country: "Poland", lat: 50.0522, lng: 19.9480, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-09", site_name: "Oskar Schindler's Enamel Factory & Eagle Pharmacy", site_city: "Krakow", site_country: "Poland", lat: 50.0478, lng: 19.9566, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-11", site_name: "Galicia Jewish Museum", site_city: "Krakow", site_country: "Poland", lat: 50.0522, lng: 19.9480, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-12", site_name: "Galicia Jewish Museum", site_city: "Krakow", site_country: "Poland", lat: 50.0522, lng: 19.9480, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-10", site_name: "Auschwitz-Birkenau Memorial and Museum", site_city: "Oswiecim", site_country: "Poland", lat: 50.0274, lng: 19.2038, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-14", site_name: "Memorial de la Shoah", site_city: "Paris", site_country: "France", lat: 48.8549, lng: 2.3526, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-15", site_name: "Memorial de la Shoah", site_city: "Paris", site_country: "France", lat: 48.8549, lng: 2.3526, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-16", site_name: "Memorial de la Shoah", site_city: "Paris", site_country: "France", lat: 48.8549, lng: 2.3526, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-17", site_name: "Memorial de la Shoah", site_city: "Paris", site_country: "France", lat: 48.8549, lng: 2.3526, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-18", site_name: "Imperial War Museum Holocaust Galleries", site_city: "London", site_country: "United Kingdom", lat: 51.4963, lng: -0.1090, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-19", site_name: "Imperial War Museum Holocaust Galleries", site_city: "London", site_country: "United Kingdom", lat: 51.4963, lng: -0.1090, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-21", site_name: "The Wiener Holocaust Library", site_city: "London", site_country: "United Kingdom", lat: 51.5210, lng: -0.1444, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-22", site_name: "The Wiener Holocaust Library", site_city: "London", site_country: "United Kingdom", lat: 51.5210, lng: -0.1444, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-23", site_name: "The Wiener Holocaust Library", site_city: "London", site_country: "United Kingdom", lat: 51.5210, lng: -0.1444, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
  { date: "2026-06-24", site_name: "The Wiener Holocaust Library", site_city: "London", site_country: "United Kingdom", lat: 51.5210, lng: -0.1444, region: "wwii-europe", subtopic: "The Holocaust", visit_date: "Jun 2026" },
]

async function seed() {
  console.log('Seeding users...')
  for (const u of seedUsers) {
    const hash = await bcrypt.hash(u.password, 10)
    await sql`
      INSERT INTO users (email, password_hash, name, role)
      VALUES (${u.email}, ${hash}, ${u.name}, ${u.role})
      ON CONFLICT (email) DO UPDATE SET password_hash = ${hash}, name = ${u.name}, role = ${u.role}
    `
  }
  console.log(`  ${seedUsers.length} users upserted`)

  console.log('Seeding trip_days...')
  for (const d of tripDays) {
    await sql`
      INSERT INTO trip_days (date, day_label, city, accom_name, accom_checkin, accom_checkout, accom_address, accom_lat, accom_lng, family_activity, boys_activity, ck_site_name, ck_site_address, ck_site_lat, ck_site_lng, hj_networking, remarks, transit_note)
      VALUES (${d.date}, ${d.day_label}, ${d.city}, ${d.accom_name}, ${d.accom_checkin}, ${d.accom_checkout}, ${d.accom_address}, ${d.accom_lat}, ${d.accom_lng}, ${d.family_activity}, ${d.boys_activity}, ${d.ck_site_name}, ${d.ck_site_address}, ${d.ck_site_lat}, ${d.ck_site_lng}, ${d.hj_networking}, ${d.remarks}, ${d.transit_note})
      ON CONFLICT (date) DO NOTHING
    `
  }
  console.log(`  ${tripDays.length} trip days inserted`)

  console.log('Seeding ck_research_entries...')
  for (const e of ckResearchEntries) {
    const dayRows = await sql`SELECT id FROM trip_days WHERE date = ${e.date}`
    const tripDayId = dayRows[0]?.id
    if (!tripDayId) {
      console.warn(`  No trip_day found for date ${e.date}, skipping`)
      continue
    }
    await sql`
      INSERT INTO ck_research_entries (trip_day_id, site_name, site_city, site_country, lat, lng, region, subtopic, visit_date)
      VALUES (${tripDayId}, ${e.site_name}, ${e.site_city}, ${e.site_country}, ${e.lat}, ${e.lng}, ${e.region}, ${e.subtopic}, ${e.visit_date})
    `
  }
  console.log(`  ${ckResearchEntries.length} research entries inserted`)

  console.log('Done!')
}

seed().catch(console.error)
